---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg
    state: present
    update_cache: yes

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
    state: present
    filename: docker

- name: Update apt cache after adding Docker repo
  apt:
    update_cache: yes

- name: Install Docker and dependencies
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: yes

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Copy Flask app and Dockerfile
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: 'roles/diwali_docker/files/app.py', dest: '/home/ubuntu/app.py' }
    - { src: 'roles/diwali_docker/files/Dockerfile', dest: '/home/ubuntu/Dockerfile' }

- name: Build Docker image
  command: docker build -t diwali-app /home/ubuntu
  args:
    chdir: /home/ubuntu

- name: Run Docker container
  command: docker run -d -p 5000:5000 diwali-app
  args:
    chdir: /home/ubuntu
